### ISSUE TITLE
Download URL points to old zip file.  "Update" updates you to v1.1.0 from v1.1.0

### ISSUE THREAD

**Issue by Sinaloit** [drexl93/pf2e-rsc#2]
When updating you update to v1.1.0 as the URL in the manifest points to an old .zip.
You could use tags/releases to create a new zip file and have the manifest point to that file
example: https://github.com/League-of-Foundry-Developers/pf2edragruler

**Comment by drexl93** [comment]
Thank you for the heads up! I just forgot to upload the new zip file. I think it should work now.

**Comment by Sinaloit** [comment]
Thanks, working fine now!
