### ISSUE TITLE
v10 update

### ISSUE THREAD

**Issue by MarkPearce** [drexl93/pf2e-rsc#5]
Hi,

I've updated your mod for v10. Fixes changes in the data model and manifest. (even know enough to update the compendium this time) but it would no longer be v9 compatible.

 you can copy over the changes and update your manifest if you like or I could submit it as a PR too... but i guess then you'd lose v9 support, unless you want to keep a branch.  Depend how you want to handle it.
 
https://github.com/MarkPearce/pf2e-rsc

**Comment by drexl93** [comment]
Hey Mark, thank you for updating it. With v10 being out for a while now, I feel comfortable transitioning it wholesale to the new version, so if you submit a PR I'll approve it.
